sleap_io/io/slp.py
sleap_io/model/labels.py

Hi, when I was exploring the library I realize that the labels object does not have the `__repr__` method that it has on the main sleap repository. I think that is useful so I added on my fork and I was wondering if it would be useful in general. Also, as the function `read_labels` is used in `main.py` to form a labels objects I propagated all the other read attributes to it so they are accessible at the top level and not only nested in the labeled frames.
Let me know if this is a a good idea, if I am missing something and also if you would like tests of some kind.

Added dunder `__repr__` to labels object

---

.github/workflows/ci.yml
sleap_io/io/utils.py
tests/io/test_utils.py

Add utilities to write to pre-existing hdf5 files. Adds utilities that (over)write datasets, groups, and attributes.
---
Other minor updates:
- [Fix ci.yml to run either on PR or Push](https://github.com/talmolab/sleap-io/pull/11/commits/1c800957699ff5e4690f1d23d22098c6f422f7d9)
No.

Add write utilities

---

sleap_io/model/instance.py
tests/model/test_instance.py

Changes to data model to enable sensible equality semantics for `Point`s and `Instance`s.
- Fix equality of `Points`. `X` and `Y` coordinates were previously compared using normal float equality semantics. Here we change to utilize the `numpy.isclose()` method for comparison, where two floats are compared for equality within some tolerance (we use just the default tolerances). Additionally, we will consider that two `NaN` values are equal, which is normally not true.
- Allow `Instance` objects to be compared for equality. The `Instance.points` collections compared with the rule that both collections of points must contain the same set of nodes, and for each node the point must be equal according to the semantics described above for `Point`s.
[list open issues here]
:heart:

Change equality semantics for Points and Instances

---

sleap_io/io/nwb.py
tests/io/test_nwb.py

I realized that there is a bug when writing more than one track and propagating metadata. In the code, the metadata dictionary drops the timestamps and the rate for each track. Because of python copying mechanism this means that those fields are not available for the second track metadata once they are droped. The solution is to create a local copy of the metadata before any modification. This PR fixes the bug and introduces a test for correctly propagating the rate.
[list open issues here]
:heart:

Metadata not correctly propagated to nwb bug

---

sleap_io/io/nwb.py
tests/io/test_nwb.py

When passing the timestamps for an nwb file `build_track_pose_estimation_list`  determines whther the timestamps for that specific node have a uniform sampling rate of not. If it does, then PoseEstimationSeries is written with a rate instead of a with timestamps* (to save space in the final nwbfile).  
However, an edge case can occur when the timestamps corresponding to a node have uniform sampling rate but their first frame included that has a prediction is not the first one in the video. In that case is necessary to write both the sampling rate and the starting time in the nwbfile for correct provenance. This PR addresses this and modifies the corresponding testing to account for this case.
*This is usually not the case as not all frames might contain predictions for that node leading …

Add propagation of start time when writing nwbfile

---

codecov.yml
setup.cfg
sleap_io/__init__.py
sleap_io/io/labelstudio.py
sleap_io/io/main.py
sleap_io/io/nwb.py
sleap_io/io/utils.py
sleap_io/model/skeleton.py
tests/fixtures/labelstudio.py
tests/io/test_labelstudio.py
tests/io/test_main.py
tests/io/test_nwb.py

This refactor cleans up #23 and #26 ahead of a v0.0.2 release.
- High-level API cleaned up to `load_nwb`, `save_nwb`, `load_labelstudio`, `save_labelstudio`
- Basic NWB loading support
- Add Label Studio functionality for inferring nodes.
[list open issues here]
:heart:

Refactoring pre v0.0.2

---

pyproject.toml

Fix the build process which was failing when uploading to PyPI after #32. This was happening since we switched to `pyproject.toml` and failing to set the `readme` attribute as dynamic so that it would pull in the `README.md` appropriately to fill the `long_description` field of the package metadata.

Fix build by including readme correctly in pyproject.toml

---

sleap_io/__init__.py
sleap_io/model/labels.py
tests/model/test_labels.py

This PR adds `Labels.find()` and `Labels.video` following the core SLEAP implementations.
Note: Since we don't have a labels cache, the `Labels.find()` implementation will be highly inefficient for many query types or datasets.

Add Labels.find and Labels.video

---

sleap_io/io/slp.py
tests/io/test_slp.py

This PR fixes automatic instantiation of video backend when loading SLP files since they use `"."` as the marker for embedded labels.

Fix detection of embedded images when loading SLP files

---

sleap_io/model/labeled_frame.py

Fix docstring for LabeledFrame.predicted_instances

---

sleap_io/io/slp.py

The `"negative_anchors"` key in the metadata for SLP files needed to be a dictionary to be unstructured appropriately in core SLEAP.

Fix serialization for negative anchors metadata field in SLP files

---

sleap_io/model/skeleton.py
tests/model/test_skeleton.py

This PR fixes #58 to allow for the `src, dst = skeleton.edges[0]` API.
The issue was that we needed to raise a `IndexError` rather than `ValueError` to comply with the [object subclassing API](https://docs.python.org/3/reference/datamodel.html#object.__getitem__) for `__getitem__`.

Fix edge unpacking

---

pyproject.toml
sleap_io/__init__.py

- Bump package to v0.1.0
- Expand `pyproject.toml` version range to include Python 3.7, which is technically compatible via pip-only install

Bump to v0.1.0

---

docs/index.md
sleap_io/io/main.py
sleap_io/io/nwb.py
sleap_io/io/slp.py
sleap_io/io/utils.py
sleap_io/model/labels.py
sleap_io/model/video.py
tests/io/test_slp.py
tests/model/test_video.py

This PR adds more flexibility and a safer path for loading SLP files in cases where the video files might not be accessible.
- Catches more I/O errors when checking if the video is accessible (addresses #116).
- Explicit control over whether video files should be opened when loading labels with:`sio.load_slp(..., open_videos=False)`
- Explicit control over whether backend is auto-initialized when creating or using `Video` objects with `Video(..., open_backend=False)`.
- More sanitization of filenames to posix/forward-slash safe forms when reading and writing SLP files.
- Added `sio.io.utils.is_file_accessible` to check for readability by actually reading a byte. This catches permission and other esoteric filesystem errors.

Safer video loading from SLP

---

sleap_io/io/slp.py
sleap_io/model/labels.py
tests/model/test_labels.py

This pull request fixes the split calculation in the `make_training_splits` function and adds the option to not embed user-labeled frame images in the saved files.
- Fix: The function now correctly splits the labels into training, validation, and test sets based on the specified proportions (fixes #117).
- Enhancement: `Labels.make_training_splits(..., embed=False)`
Previously, the function would always embed the images, which could be slow for large projects. With this change, the `embed` parameter is introduced, allowing the user to choose whether to embed the images or save the labels with references to the source video files.

Fix split calculation and allow for not embedding

---

sleap_io/model/labeled_frame.py
sleap_io/model/labels.py
sleap_io/model/video.py
tests/model/test_labels.py
tests/model/test_video.py

- `LabeledFrame.frame_idx`: Now always converted to `int` type.
- `Video.close()`: Now caches backend metadata to `Video.backend_metadata` to persist metadata on close.
- `copy.deepcopy()` now works on `Video` objects even if backend is open.
- `Video.save(save_path: str | Path, frame_inds: list[int] | np.ndarray | None = None, video_kwargs: dict[str, Any] | None = None)`: Method to save a video file to an MP4 using `VideoWriter` with an optional subset of frames.
- `Labels.extract(inds: list[int] | list[tuple[Video, int]] | np.ndarray, copy: bool = True)`: Add method to extract a subset of frames from the labels, optionally making a copy, and return a new `Labels` object.
- `Labels.trim(save_path: str | Path, frame_inds: list[int] | np.ndarray, video: Video | int | None = None, …

Add `Labels.extract`, `Labels.trim` and `Video.save`

---

.github/workflows/ci.yml
pyproject.toml
sleap_io/io/nwb.py
tests/io/test_nwb.py

This adds support for the ndx-pose > 0.2.0 for structures such as `PoseEstimationSeries`, `PoseEstimation` and the newly introduced "Skeleton" and "Skeletons" container.
I am aware that there is larger effort to use the training related structure of ndx-pose > 0.2.0 on #104 but I thought this effort could be divided (and that way the PR simplified) into a PR for post-training structures (this) and one for the training structures (#104).
Let me know what you think.

Add support for writing to nwb with ndx-pose > 0.2.0

---

sleap_io/model/camera.py
tests/model/test_camera.py

It's time to integrate the multiview classes into sleap-io! This will be a collection of stacked PRs with this very first PR adding the `Camera` class and the very last PR implementing serialization/deserialization of the `RecordingSession` class.

Add `Camera` class

---

tests/io/test_nwb.py

NWB right now scales quite poorly with number of nodes and frames, totally dominating our CI time.
This PR mitigates this by reducing the number of frames in the test data.

Minimize NWB testing time

---

sleap_io/model/labels.py
tests/model/test_labels.py

Introduce a method to synchronize instances with numpy arrays, allowing for updates and the creation of new instances based on modified data. Include tests to verify functionality and correctness of updates.
---
**Note:** This PR was implemented entirely through *vibes* using the following prompt + GitHub Copilot in Agent mode with Claude 3.7 Sonnet and thinking mode:
```
Can you add a `update_from_numpy` method to the `Labels` class?
This should take the output of `Labels.numpy()` and update the corresponding `Instance` and `PredictedInstance` objects and their underlying `PointsArray` data in place.
- The numpy array is specific to a single video, so this should need to be specified as an input argument unless it is a single-video project, in which case it's automatically inferred.
- …
```

Implement `update_from_numpy` method for instance updating from tracks array

---

sleap_io/model/camera.py
tests/model/test_camera.py

This PR adds much needed repr methods for the MV classes. This is what the repr output looks like:
```python
Camera(matrix=identity, dist=zero, size=None, rvec=[0.   0.   0.64], tvec=[ 1.8 -2.4  0. ], name=None)
CameraGroup(cameras=2:[camera_0, camera_1])
InstanceGroup(cameras=2:[None, None])
FrameGroup(frame_idx=0,instance_groups=1,cameras=2:[None, None])
RecordingSession(camera_group=2cameras, videos=2, frame_groups=1)
```
.

Add repr for mv classes

---

environment.yml

To match the `ndx-pose` dependency version in pyproject.toml introduced in #143

Update ndx-pose dependency to version >=0.2.1 in environment.yml

---

.github/copilot-instructions.md
sleap_io/model/camera.py
tests/model/test_camera.py

Replace the use of OpenCV's Rodrigues function with a custom implementation for converting between rotation vectors and rotation matrices. This change eliminates the dependency on OpenCV for this functionality.

Remove OpenCV dependency for Rodrigues transformation

---

.github/workflows/ci.yml
docs/examples.md
docs/model.md
sleap_io/model/camera.py
sleap_io/version.py

- Bumped to v0.3.0
- Include an example demonstrating how to convert labels to and from numpy arrays for easier manipulation during temporal filtering operations.

Bump to v0.3.0

---

pyproject.toml
sleap_io/io/main.py
sleap_io/io/skeleton.py
tests/data/slp/flies13.skeleton.yml
tests/fixtures/slp.py
tests/io/test_skeleton_io.py

This PR adds YAML format support for skeleton serialization, providing a more human-readable alternative to the JSON/jsonpickle format.
This builds on #178 by adding YAML as an additional format for skeleton files. The YAML format is designed to be:
- Human-readable and editable
- Simpler than the jsonpickle JSON format
- Suitable for manual skeleton creation and editing
1. **`SkeletonYAMLDecoder`** - Decodes skeletons from YAML format
- Handles both single skeletons and multiple skeletons with names as keys
- Provides `decode_dict()` method for embedded skeleton data
2. **`SkeletonYAMLEncoder`** - Encodes skeletons to YAML format
- Produces clean, human-readable YAML
- Provides `encode_dict()` method for embedding in larger YAML structures
```yaml
Skeleton-0:
nodes:
- name: head
- name: …
```

Add YAML support for skeleton serialization

---

.github/workflows/claude-code-review.yml
sleap_io/io/main.py
sleap_io/io/skeleton.py
sleap_io/io/slp.py
tests/io/test_skeleton_io.py

This PR implements several quality-of-life enhancements for skeleton handling in sleap-io:
- **API Enhancement**: Renamed `SkeletonSLPDecoder.decode_skeletons()` to `decode()` for consistency with other decoder classes
- **Enhanced `load_skeleton()`**: Now supports multiple file formats:
- `.slp` files - extracts skeletons directly from SLEAP project files
- Training config JSON files - automatically detects and extracts embedded skeletons from `data.labels.skeletons` field
- Existing support for standalone skeleton JSON/YAML files remains unchanged
- **Improved test coverage**: Added comprehensive tests achieving 100% coverage for new functionality
```
- Enhanced `load_skeleton()` to support loading skeletons from .slp files and training config JSON files
- Renamed …
```

Skeleton API enhancements

---

sleap_io/model/labels.py

This pull request addresses an edge case in the `merge` method of the `sleap_io/model/labels.py` file when merging videos with duplicate images present in both datasets. The fix ensures that frame indices are correctly mapped even when an image is a duplicate. 
Close #239 .

Improve duplication handling in `Labels.merge()`. 

---

docs/merging.md
sleap_io/model/labeled_frame.py
sleap_io/model/labels.py
sleap_io/model/matching.py
tests/model/test_labeled_frame.py
tests/model/test_merging_integration.py

In this PR, the `smart` merge strategy is updated for cases where both instances are predictions. Previously, the instance with the higher score was selected. Now, when both are predicted instances, the newer prediction is always chosen.
This PR also introduces a new `update_tracks` merge strategy for `LabeledFrame.merge()` that allows updating track assignments and tracking scores while preserving original pose annotations.

Update merge strategy
